#!/usr/bin/env bash
#installing Nginx on web
#should listen to prt 80

1-install_nginx_web_serversudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/hello.html
sudo service nginx start