#!/usr/bin/env bash
#installing Nginx on web
#should listen to prt 80

sudo apt-get -y upgrade
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /usr/share/nginx/html/hello.html
