#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.
i=1
while [ "$i" -lt 101 ]
do
    if [ $((i%15)) = 0 ]
    then
	echo "Fizzbuzz"
    elif [ $((i%3)) = 0 ]
    then
	 echo "Fizz"
    elif [ $((i%5)) = 0 ]
    then
	echo "Buzz"
    else
	echo "$i"
    fi
((i++))
done
