#!/usr/bin/env bash
# Fixes container same as task 1 with less 7 lines 
sudo chown nginx: /etc/nginx/nginx.conf
sudo chmod u+r /etc/nginx/nginx.conf
pkill apache
sudo sed -i -e 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx nginx -c /etc/nginx/nginx.conf
